### PR TITLE
Browserify support for generator

### PR DESCRIPTION
**Pull request by Qwerios**
As promised in https://github.com/tmaximini/generator-ionic-gulp/issues/16 here is the pull request for optional browserify support.

I've included an updated README. Please let me know if anything isn't clear so I can amend it if needed.

I also took the liberty of adding a version bump

As a bonus I added support to fill name/email using the know git user details :)

### CODE REVIEW

**Comment by tmaximini** [comment]
hey man, this looks awesome. Thank you for this. I'll test it asap. one thing I noticed, the name in ngDocs comments seems to be fixed to `CTASpore`, maybe we can make it dynamic as with the module names, injecting `<%= ngModulName %>`

**Comment by Qwerios** [comment]
My bad. I missed a few references it seems. I've amended the pull request. You have cleverly deduced the name of the first project I intend to create with your generator. Guess the cat is out of the bag...

**Comment by Qwerios** [comment]
Right, that last commit should fix the last issues with applying the template variables.

**Comment by tmaximini** [comment]
thanks, man. Quality PR :+1:

**Pull request merged**
